name: ML Retraining Pipeline

on:
  push:
    paths:
      - "data/raw/housing.csv.dvc"

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remote
        run: |
          dvc remote add -d localstorage dvc_storage -f

      - name: Status dataset (DVC)
        run: dvc status

      - name: Pull dataset (DVC)
        run: dvc pull -f

      - name: Run data validation + retraining pipeline
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: python -m src.pipeline.update_pipeline

      - name: Upload MLflow tracking DB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-db
          path: mlflow.db